### ISSUE TITLE
Proposal to switch to Oblogout

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Archlabs-Exit#2]
hhh at BL Forum has proposed that BL returns to their classic look for the exit which is a small dialog box with the exit options. 
https://forums.bunsenlabs.org/viewtopic.php?id=3542

I'd like to propose we drop the awkward AL/BL-Exit and return to oblogout with Sardi as the theme.

Please add your input @toola69 @erikdubois @osgyan

**Comment by Dobbie03** [comment]
This is one of the times I am really happy to move away from the default BL look.  I have never like AL/BL-Exit and prefer oblogout anyway.

**Comment by erikdubois** [comment]
I would prefer oblogout as well
using it now

**Comment by Dobbie03** [comment]
I am too, I have avoided the AL-Exit.

**Comment by erikdubois** [comment]
do i have a go to use oblogout?

**Comment by toola69** [comment]
I want oblogout

**Comment by erikdubois** [comment]
since we have switched to oblogout
this repo can be deleted.
I leave it up to @Dobbie03 to decide

**Comment by Dobbie03** [comment]
Can we archive?

**Comment by erikdubois** [comment]
if you can archive on your local computer
yes then we can archive

**Comment by Dobbie03** [comment]
I have git cloned to my desktop.

Closing and deleting this repo.
